name: meiliteahouse-website
recipe: laravel
config:
    webroot: ./public
    php: '8.2'
proxy:
    appserver:
        - meiliteahouse-website.localhost
services:
    appserver:
        scanner: false
    database:
        type: mysql
        portforward: 33071
        creds:
            user: username
            password: password
            database: meiliteahouse
    node:
        type: node:18
        scanner: false
        ports:
            - '5181:5181'
            - '13711:13711'
        build:
            - yarn install && yarn build
tooling:
    node:
        service: appserver
    yarn:
        service: node
    dev:
        service: node
        cmd: yarn dev
    build:
        service: node
        cmd: yarn build
