name: meiliteahouse-website
recipe: laravel
config:
  webroot: ./public
  php: "8.2"
proxy:
  appserver:
    - meiliteahouse-website.localhost
services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_19.x | bash -
      - apt-get install -y nodejs
  database:
    type: mysql
    portforward: 33066
    creds:
      user: username
      password: password
      database: meiliteahouse
  node:
    type: node
    scanner: false
    ports:
      - "5176:5176"
    build:
      - yarn install && yarn build
tooling:
  node:
    service: appserver
  yarn:
    service: node
  dev:
    service: node
    cmd: yarn dev
  build:
    service: node
    cmd: yarn build
